import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";
import requests from "../utils/requests";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Home() {
  const router = useRouter();
  const [movies, setMovies] = useState([]);
  useEffect(() => {
    const genre = router.query.genre;
    async function getData() {
      const result = await fetch(
        `https://api.themoviedb.org/3${
          requests[router.query.genre]?.url || requests.fetchTopRated.url
        }`
      ).then((res) => res.json());
      return setMovies(result.results);
    }
    getData();
  }, [router.query.genre]);
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Nav />
      <Result movies={movies} />
    </div>
  );
}
// export async function getServerSideProps(context) {
//   const genre = context.query.genre;
//   const request = await fetch(
// `https://api.themoviedb.org/3${
//   requests[genre]?.url || requests.fetchTopRated.url
// }`
//   ).then((res) => res.status(200).json());
//   return {
//     props: {
//       result: request.results,
//     },
//   };
// }
